//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bolhaya_pachka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int id_agent { get; set; }
        public string name_company { get; set; }
        public string type { get; set; }
        public string juridical_adress { get; set; }
        public int INN { get; set; }
        public string KPP { get; set; }
        public string full_name_director { get; set; }
        public int phone { get; set; }
        public string email { get; set; }
        public byte[] logo { get; set; }
        public string priority_in_deliveries { get; set; }
        public string points_of_sale { get; set; }
        public string name_attribute { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
