//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bolhaya_pachka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Agents = new HashSet<Agent>();
            this.productions = new HashSet<production>();
        }
    
        public int Id_product { get; set; }
        public int article { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public byte[] image { get; set; }
        public decimal minimum_cost { get; set; }
        public int size { get; set; }
        public int weight_without_packaging { get; set; }
        public int weight_with_packaging { get; set; }
        public byte[] quality_certificate { get; set; }
        public int namber_standart { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agent> Agents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<production> productions { get; set; }
    }
}
