//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bolhaya_pachka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turnstile
    {
        public int id_turnstile { get; set; }
        public int id_worker { get; set; }
        public System.DateTime date_n_time { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
